In [ ]:
###### Comment Legend ######

    # Describing a function
    ### Describing an issue
    ###### Infomational ######

###### To Do List ######

    # Create live showing of relationship on returned detection images # Almost Done
    # Create a function to save bad images for later use
    # 

In [1]:
import cv2
import os
import math
import pandas as pd
from time import sleep
import numpy as np
from matplotlib import pyplot as plt


%run utils/segmentation/detect.ipynb
%run utils/superimposition/functions.ipynb
%run utils/extraction/objClass.ipynb

In [9]:
###### Testing on a Single Frames/Photos ######

### Fix to make actually work with new Stereo, its a useful tool

s = 0.4

segmentation_weights = "yolov5s-seg.pt"
weights = "yolov7-tiny.pt"

thermal = cv2.imread("photos/thermal.jpeg")
stereo = cv2.imread("photos/stereo.jpg")
rgb = cv2.imread("photos/rgb.jpg")

# print(thermal.shape, stereo.shape, rgb.shape)

images = [thermal, stereo, rgb]

path = "utls/segmentation/"
os.chdir(path)
segmentation_model = loadModel(segmentation_weights)
path = "../.."
os.chdir(path)

scales, offset= calibration(images.copy(), segmentation_model)
print(offset)
print(scales)

images = modify_images(images.copy(), scales, offset)

cv2.imshow('thermalCam', cv2.resize(images[0], (int(images[0].shape[0]*s), int(images[0].shape[1]*s))))
cv2.imshow('stereoCam', cv2.resize(images[1], (int(images[1].shape[0]*s), int(images[1].shape[1]*s))))
cv2.imshow('webCam', cv2.resize(images[2], (int(images[2].shape[0]*s), int(images[2].shape[1]*s))))
cv2.waitKey(1)

masks, _ = detectObjects(images[2], model, conf_thres=0.60)
SII = apply_mask(images, segmentation_model, scales, masks)

cv2.imshow("hh", cv2.resize(SII, (640, 640)))
cv2.waitKey(1)

Fusing layers... 
YOLOv5s-seg summary: 224 layers, 7611485 parameters, 0 gradients, 26.4 GFLOPs


UnboundLocalError: local variable 'masks' referenced before assignment

In [2]:
###### Video Processor ######

# import pickle
import os

# Model used for segmentation
segmentation_weights = "yolov7-seg.pt"
BB_weights = "yolov7-tiny.pt"

### Can I do anything about this?
# Something required to make the detect function work
path = "utils/segmentation/"
os.chdir(path)
segmentation_model = loadModel(segmentation_weights)
BB_model = loadModel(BB_weights)
path = "../.."
os.chdir(path)

# Formatting for mp4 video
fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')

# What frame rate to be used
fps = 10

# Used to select a folder
fileList = os.listdir("videos")
fileName = fileList[1]
print(fileList, "\nSelected File:", fileName)
IsFileCorrect = input()

# Grab videos from final location selected
rgbVideo = cv2.VideoCapture(f"videos/{fileName}/rgbout.mp4")
thermalVideo = cv2.VideoCapture(f"videos/{fileName}/thermalout.mp4")
stereoVideo = cv2.VideoCapture(f"videos/{fileName}/stereoout.mp4")
leftVideo = cv2.VideoCapture(f"videos/{fileName}/leftout.mp4")

# Frame counter
calibrationCount = 0
frameCount = 0

# Skip in video until first object is in clear location on screen
skip = 200

rgbVideo.set(cv2.CAP_PROP_POS_FRAMES, skip)
thermalVideo.set(cv2.CAP_PROP_POS_FRAMES, skip)
stereoVideo.set(cv2.CAP_PROP_POS_FRAMES, skip)
leftVideo.set(cv2.CAP_PROP_POS_FRAMES, skip)

ObjList = Object_List()

### Get to work with object infomation extraction


# Actual Loop which goes through all frames and moves as appropriate
while(True): 

    # Read from all videos a single frame
    ret, Rgbframe = rgbVideo.read()
    ret1, Thermalframe = thermalVideo.read()
    ret2, Stereoframe = stereoVideo.read()
    ret3, leftFrame = leftVideo.read()
    
    # If any of the videos end then end processing
    if not (ret & ret1 & ret2 and ret3):
        break
    
    # Compile images 
    images = [Thermalframe, leftFrame, Rgbframe]
    
    # Every 100th frame preform calibration 
    if calibrationCount % 10 == 0:

        print("\nCalibrating Image")
        scales, offset, minImageSize = calibration(images.copy(), BB_model)

        if scales != None and offset != None:

            # Set backup values since these currently work
            backupScales = scales
            backupoffset = offset
            BackupminImageSize = minImageSize

            print("New Offset, Scales and Mininim Image Size:\n", offset, "\n", scales, "\n", minImageSize)
        else:

            # If error/false flag occurs try again in five frames keep current configuration 
            calibrationCount-=5
            scales = backupScales
            offset = backupoffset
            minImageSize = BackupminImageSize

            print("Setting Scale and Offset to Backup Values")

    
    # Convert stereoframe into colors for visualization 
    
    Stereoframe = cv2.cvtColor(Stereoframe, cv2.COLOR_BGR2GRAY)

    images[1] = Stereoframe

    # Modify images based on calibration settings
    
    non_related_SII = superimpose_images(images.copy(), addColor=True)
                                                   
    images = modify_images(images.copy(), scales, offset.copy(), minImageSize)
    
    related_SII = superimpose_images(images.copy(), addColor=True)

    # Detections from RGB image
    masks, rgbImgDetections = detectObjects(images[2], segmentation_model, conf_thres=0.60)
    
    if torch.cuda.is_available() and masks != None:
        masks = masks.cpu()
    
    ObjList.appendObjects(images, frameCount, rgbImgDetections, masks)
    
    Stereoframe = images[1]
    StereoframeMapped = cv2.normalize(images[1], None, 255, 0, cv2.NORM_INF, cv2.CV_8UC1)
    StereoframeMapped = cv2.equalizeHist(StereoframeMapped)
    StereoframeMapped = cv2.applyColorMap(StereoframeMapped, cv2.COLORMAP_JET)
    images[1] = StereoframeMapped
    
    # Produce superimposed Image based on previous relationships
    SII = apply_mask(images.copy(), segmentation_model, scales, masks)
    
    images[1] = Stereoframe

    # Create video to process 
    if calibrationCount==0:

        thermalout = cv2.VideoWriter(f"videos/{fileName}/processed/thermal_sii.mp4", fourcc, fps, (images[0].shape[1], images[0].shape[0]))
        stereoout = cv2.VideoWriter(f"videos/{fileName}/processed/stereo_sii.mp4", fourcc, fps, (images[1].shape[1], images[1].shape[0]), 0)
        webout = cv2.VideoWriter(f"videos/{fileName}/processed/rgb_sii.mp4", fourcc, fps, (images[2].shape[1], images[2].shape[0]))
        SIIout = cv2.VideoWriter(f"videos/{fileName}/processed/SII.mp4", fourcc, fps, (SII.shape[1], SII.shape[0]))

    # Write frames to all the videos
    thermalout.write(images[0])
    stereoout.write(images[1])
    webout.write(images[2])
    SIIout.write(SII)

    # Show Images 
    cv2.imshow('thermalCam', images[0])
    cv2.imshow('stereoCam', StereoframeMapped)
    cv2.imshow('rgbCam', images[2])
    cv2.imshow('non_related_SII', non_related_SII)
    cv2.imshow('related_SII', related_SII)
    cv2.imshow('SII', SII)

    # Increment frame count
    calibrationCount+=1
    frameCount+=1

    prevOffset = offset

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

print("\nProcessing Ended. Saving videos...")
        
# Save all videos
SIIout.release()
webout.release()
thermalout.release()
stereoout.release()

print("Saving complete!")

csv = ObjList.createDataframe()
csv.to_csv(f"videos/{fileName}/processed/object_list.csv", index=False)

### Create a function that grabs all frames that broke the function

cv2.destroyAllWindows()

Fusing layers... 
yolov7-iseg summary: 325 layers, 38268602 parameters, 0 gradients, 143.2 GFLOPs
Fusing layers... 
yolov7-tiny summary: 200 layers, 6219709 parameters, 6219709 gradients
C:\ProgramData\Anaconda3\lib\site-packages\torch\_tensor.py:1104: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at  C:\cb\pytorch_1000000000000\work\build\aten\src\ATen/core/TensorBody.h:475.)
  return self._grad


['2022-12-01_18-03-33', '2022-12-02_13-05-04', '2022-12-08_12-49-00', 'newStereo', 'outside_test', 'SII', 'stereo.mp4', 'thermal.mp4', 'track_test.mp4', 'track_test2.mp4', 'webcam.mp4'] 
Selected File: 2022-12-02_13-05-04



Calibrating Image
comparedClass:  2.0
Largest Objects selected 
 [[          2     0.38281     0.62305     0.32812     0.17188]
 [          2     0.51375     0.60375      0.3625      0.1725]
 [          2     0.47731     0.63333     0.50093     0.23889]]
Objects in Range
New Offset, Scales and Mininim Image Size:
 [[0, 0, 0, 0], [40, 9, -41, 90], [107, 70, 37, 140]] 
 [1, 1.15862065155356, 0.3105360613320855] 
 512

Calibrating Image
comparedClass:  2.0
Largest Objects selected 
 [[          2     0.18262     0.59375     0.20117     0.15234]
 [          2      0.2625       0.565       0.215        0.16]
 [          2     0.52269     0.47037     0.16019    0.068519]]
Objects are not within Range
Setting Scale and Offset to Backup Values

Calibrating Image
comparedClass:  2.0
Largest Objects selected 
 [[          2     0.29297     0.62012     0.32422     0.19336]
 [          2      0.5325      0.6225        0.47        0.25]
 [          2      0.4963     0.66019     0.64259     0.33519

,frame,objNum,cls,x,y,z,color,thermal
0,0,0,2.0,-1.813434,-2.001031,11.045081,"[78, 77, 74]",91.623562
1,0,1,2.0,-11.227893,-1.359166,20.875642,"[101, 94, 85]",67.718209
2,0,2,2.0,3.483589,-0.306250,27.046479,"[96, 92, 83]",75.691381
3,1,0,2.0,-0.791425,-2.075623,10.550155,"[81, 80, 77]",90.489988
4,1,1,2.0,-12.145851,-1.557976,22.464136,"[101, 94, 85]",66.123360
...,...,...,...,...,...,...,...,...
222,315,3,2.0,4.494109,-2.179372,9.563804,"[72, 60, 48]",104.361132
223,316,3,2.0,5.052219,-2.304034,9.806317,"[71, 59, 48]",102.298843
224,317,3,2.0,4.697057,-2.088954,8.733080,"[71, 59, 50]",101.167811
225,318,3,2.0,5.460455,-2.191783,8.951106,"[89, 75, 66]",101.295916


In [6]:
SIIout.release()
webout.release()
thermalout.release()
stereoout.release()

In [5]:
csv = ObjList.createDataframe()
csv.to_csv(f"videos/{fileName}/processed/object_list.csv", index=False)

,frame,objNum,cls,x,y,z,color,thermal
0,0,0,2.0,-1.795583,-2.014176,11.031457,"[79, 78, 74]",91.573660
1,0,1,2.0,-11.308432,-1.368915,21.025384,"[104, 96, 87]",67.204392
2,0,2,2.0,3.552204,-0.305566,26.986096,"[93, 88, 80]",75.294067
3,1,0,2.0,-0.799104,-2.095763,10.652523,"[81, 82, 79]",90.423784
4,1,1,2.0,-12.445386,-1.571711,22.662186,"[106, 98, 89]",65.268361
...,...,...,...,...,...,...,...,...
210,315,3,2.0,4.507316,-2.212929,9.591909,"[73, 61, 49]",104.424272
211,316,3,2.0,5.037796,-2.303786,9.805260,"[71, 59, 48]",101.986947
212,317,3,2.0,4.684613,-2.069657,8.756027,"[72, 61, 50]",100.653781
213,318,3,2.0,5.413084,-2.170281,8.914820,"[90, 77, 68]",101.005902
