In [1]:
###### This program is used to run all the cameras at the sametime at the same framerate ######
# https://docs.luxonis.com/en/latest/pages/faq/

import os
import cv2
import time
import numpy as np
import depthai as dai
from datetime import datetime


# Creates a pipeline for extracting infomation from the Stereo Camera
def createNewPipeline(rgb=True, left=True, right=True, stereo=True):
    
    # Creates pipeline from dai API
    pipeline = dai.Pipeline()
    
    # If an rgb camera is in use then set it up
    if rgb:
        # Create RGB cam pipline
        camRgb = pipeline.create(dai.node.ColorCamera)
        
        # Set the correct socket to communicate with the pipeline and set resolution
        camRgb.setBoardSocket(dai.CameraBoardSocket.RGB)
        camRgb.setResolution(dai.ColorCameraProperties.SensorResolution.THE_1080_P)
        # camRgb.setVideoSize(1920, 1080)
        
        # Link pipeline to output node
        xoutRgb = pipeline.create(dai.node.XLinkOut)
        xoutRgb.setStreamName("rgb")
        camRgb.video.link(xoutRgb.input)

    if left:
        monoLeft = pipeline.create(dai.node.MonoCamera)

        monoLeft.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
        monoLeft.setBoardSocket(dai.CameraBoardSocket.LEFT)

        xoutLeft = pipeline.create(dai.node.XLinkOut)
        xoutLeft.setStreamName("left")
        monoLeft.out.link(xoutLeft.input)

    if right:
        monoRight = pipeline.create(dai.node.MonoCamera)

        monoRight.setResolution(dai.MonoCameraProperties.SensorResolution.THE_400_P)
        monoRight.setBoardSocket(dai.CameraBoardSocket.RIGHT)

        xoutRight = pipeline.create(dai.node.XLinkOut)
        xoutRight.setStreamName("right")
        monoRight.out.link(xoutRight.input)
        
    if stereo:
        # Create a pipeline for developing the stereo depth
        stereo = pipeline.create(dai.node.StereoDepth)
        
        # Create configuration 
        stereo.initialConfig.setConfidenceThreshold(255)
        stereo.setLeftRightCheck(True)
        stereo.setSubpixel(False)
        
        monoLeft.out.link(stereo.left)
        monoRight.out.link(stereo.right)
        
        xoutDepth = pipeline.create(dai.node.XLinkOut)
        xoutDepth.setStreamName("depth")
        stereo.depth.link(xoutDepth.input)

    device = dai.Device(pipeline)

    output = []

    if rgb:
        rgbVideo = device.getOutputQueue(name="rgb", maxSize=1, blocking=False)
        output.append(rgbVideo)

    if left:
        leftVideo = device.getOutputQueue(name="left", maxSize=1, blocking=False)
        output.append(leftVideo)

    if right:
        rightVideo = device.getOutputQueue(name="right", maxSize=1, blocking=False)
        output.append(rightVideo)
        
    if stereo:
        # dispQ = device.getOutputQueue(name="disp", maxSize=1, blocking=False)
        depthQueue = device.getOutputQueue(name="depth", maxSize=1, blocking=False)
        output.append(depthQueue)
        output.append(stereo)

    output.append(device)
    
    return output

In [2]:
fourcc = cv2.VideoWriter_fourcc('m', 'p', '4', 'v')

RECORD = True

output = createNewPipeline()

rgbCam = output[0]
leftCam = output[1]
rightCam = output[2]
thermalCam = cv2.VideoCapture(0)
stereoCam = output[3]

stereo = output[4]

rgbFrame = rgbCam.get().getCvFrame()
leftFrame = leftCam.get().getCvFrame()
rightFrame = rightCam.get().getCvFrame()
ret, Thermalframe = thermalCam.read()
stereoFrame = stereoCam.get().getCvFrame()

print("rgbFrame:", rgbFrame.shape)
print("leftFrame:", leftFrame.shape)
print("rightFrame:", rightFrame.shape)
print("Thermalframe:", Thermalframe.shape)
print("stereoFrame:", stereoFrame.shape)

FPS = 10
timeNow = str(datetime.now())[:-7].replace(" ", "_").replace(":", "-")
print(timeNow)

if RECORD:
    base = f"videos/{timeNow}"
    os.mkdir(base)
    os.mkdir(f"{base}/processed")

    rgbout = cv2.VideoWriter(f"{base}/rgbout.mp4", fourcc, FPS, (rgbFrame.shape[1], rgbFrame.shape[0]))
    leftout = cv2.VideoWriter(f"{base}/leftout.mp4", fourcc, FPS, (leftFrame.shape[1], leftFrame.shape[0]), 0)
    rightout = cv2.VideoWriter(f"{base}/rightout.mp4", fourcc, FPS, (rightFrame.shape[1], rightFrame.shape[0]), 0)
    thermalout = cv2.VideoWriter(f"{base}/thermalout.mp4", fourcc, FPS, (Thermalframe.shape[1], Thermalframe.shape[0]), 0)
    stereoout = cv2.VideoWriter(f"{base}/stereoout.mp4", fourcc, FPS, (stereoFrame.shape[1], stereoFrame.shape[0]), 0)

print(stereoFrame.shape[1], stereoFrame.shape[0])

#time.sleep(7)
t0 = datetime.now()

while(True):
    
    # Determine the initial frame time 
    initialFrameTime = datetime.now()
          
    rgbFrame = rgbCam.get().getCvFrame()
    leftFrame = leftCam.get().getCvFrame()
    rightFrame = rightCam.get().getCvFrame()
    ret, Thermalframe = thermalCam.read()
    stereoFrame = stereoCam.get().getFrame()
    
    
    Thermalframe = cv2.cvtColor(Thermalframe, cv2.COLOR_BGR2GRAY)
    stereoFrame[0:5,0:5] = 30000 # MAX
    stereoFrame = cv2.normalize(stereoFrame, None, 255, 0, cv2.NORM_INF, cv2.CV_8UC1)
    # stereoFrame = cv2.equalizeHist(stereoFrame)
    # stereoFrame = cv2.applyColorMap(stereoFrame, cv2.COLORMAP_JET)
    
    if RECORD:
        rgbout.write(rgbFrame)
        leftout.write(leftFrame)
        rightout.write(rightFrame)
        thermalout.write(Thermalframe)
        stereoout.write(stereoFrame)
    
    rgbFrame = cv2.resize(rgbFrame, (960, 540))
    cv2.imshow('rgbFrame', rgbFrame)
    cv2.imshow('leftFrame', leftFrame)
    cv2.imshow('rightFrame', rightFrame)
    cv2.imshow('thermalCam', Thermalframe)
    cv2.imshow('stereoFrame', stereoFrame)
    
    lateFrameDifference = float( str(datetime.now() - initialFrameTime)[7:] )
    
    while (lateFrameDifference < (1/FPS)):
        lateFrameDifference = float( str(datetime.now() - initialFrameTime)[7:] )
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

        
t1 = datetime.now()

if RECORD:
    rgbout.release()
    leftout.release()
    rightout.release()
    thermalout.release()
    stereoout.release()
    thermalCam.release()

print(t1 - t0)

cv2.destroyAllWindows()

rgbFrame: (1080, 1920, 3)
leftFrame: (400, 640)
rightFrame: (400, 640)
Thermalframe: (512, 640, 3)
stereoFrame: (400, 640)
2022-12-08_12-49-00
640 400
0:00:17.650750


In [ ]:
import numpy as np
import math
import cv2
import time

def calc_spatials(depthFrame, roi=[200,200,205,205], averaging_method=np.mean):
    THRESH_LOW = 20
    THRESH_HIGH = 30000

    xmin, ymin, xmax, ymax = roi
    print(np.amax(depthFrame))
    depthFrame = depthFrame / 255 * 30000
    print(np.amax(depthFrame))

    # Calculate the average depth in the ROI.
    depthROI = depthFrame[ymin:ymax, xmin:xmax]
    inRange = (THRESH_LOW <= depthROI) & (depthROI <= THRESH_HIGH)
    print(depthROI)

    averageDepth = averaging_method(depthROI[inRange])

    centroid = { # Get centroid of the ROI
        'x': int((xmax + xmin) / 2),
        'y': int((ymax + ymin) / 2)
    }

    midW = int(depthFrame.shape[1] / 2) # middle of the depth img width
    midH = int(depthFrame.shape[0] / 2) # middle of the depth img height
    bb_x_pos = centroid['x'] - midW
    bb_y_pos = centroid['y'] - midH

    # angle_x = self._calc_angle(depthFrame, bb_x_pos)
    # angle_y = self._calc_angle(depthFrame, bb_y_pos)

    spatials = {
        'z': averageDepth,
        'x': 5,
        'y': -5
    }
    return spatials, centroid

In [4]:
stereoVideo = cv2.VideoCapture("stereoout.mp4")

y = 200
x = 300
step = 3
delta = 5

while True:
    ret, Stereoframe = stereoVideo.read()
    
    
    spatials, centroid = calc_spatials(Stereoframe)
    
    print(spatials)
        
    Stereoframe = cv2.circle(Stereoframe, (x,y), 5, (255,255,255), 5)
    cv2.imshow("Stereoframe", Stereoframe)    
    
    time.sleep(1)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

255
30000.0
[[[ 1176.47058824  1176.47058824  1176.47058824]
  [    0.             0.             0.        ]
  [ 1882.35294118  1882.35294118  1882.35294118]
  [ 2823.52941176  2823.52941176  2823.52941176]
  [ 1058.82352941  1058.82352941  1058.82352941]]

 [[  235.29411765   235.29411765   235.29411765]
  [    0.             0.             0.        ]
  [ 1058.82352941  1058.82352941  1058.82352941]
  [  352.94117647   352.94117647   352.94117647]
  [ 8941.17647059  8941.17647059  8941.17647059]]

 [[    0.             0.             0.        ]
  [    0.             0.             0.        ]
  [    0.             0.             0.        ]
  [  470.58823529   470.58823529   470.58823529]
  [10470.58823529 10470.58823529 10470.58823529]]

 [[    0.             0.             0.        ]
  [  117.64705882   117.64705882   117.64705882]
  [  941.17647059   941.17647059   941.17647059]
  [    0.             0.             0.        ]
  [    0.             0.             0.        ]]



KeyboardInterrupt: 

In [19]:
import datetime
from datetime import datetime as dt
t0 = dt.now()

fps = 1/10
frame = 1

print(fps*frame*100000)
delta = datetime.timedelta(microseconds=fps*frame*100000)
t1 = t0 + delta

print(t0)
print( t1 )

10000.0
2022-11-15 21:20:58.310720
2022-11-15 21:20:58.320720
