In [1]:
from ultralytics import YOLO
from ultralytics.yolo.utils.plotting import Annotator
import torch
import numpy as np
import os
import cv2

In [3]:
model = YOLO("yolov8l-seg.pt")

PATH = "videos/2022-12-02_13-05-04/processed/rgb_sii.mp4"

for result in model.track(source=PATH, stream=True, verbose=False):
    
    frame = result.orig_img
    print(result.masks.shape)
    
    
    combined_mask = np.zeros((640, 640), dtype=bool)

    annotator = Annotator(frame)
    print(annotator)
    
    for box in result.boxes:
        print(box.conf)
        annotator.box_label(box.xyxy[0], label=str(box.id.item()), color=(0,225,100))
        
    
    cv2.imshow("YOLO", annotator.result())
    break
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break

torch.Size([3, 640, 640])
tensor([0.90659])
tensor([0.88997])
tensor([0.86815])


In [41]:
result.masks.cpu().data.shape

torch.Size([1, 640, 640])

NameError: name 'annotator' is not defined